#!/bin/bash
# Compile and load program over CAN
# E.g. ./cc A0000000

./mm $1

cd ~/GliderWinchCommons/embed/svn_discoveryf4/PC/sensor/CANldr/trunk
./CANldr 127.0.0.1 32123 $1 ~/GliderWinchItems/bmsmot/F446/build/F446.xbin
echo $?

cd -

