#!/bin/bash
# Compile and load program over CAN
# ./cc <BMS ID> <hub-server> <port>
# E.g. ./cc A0000000 localhost 32123
# E.g. ./cc A0000000 192.168.2.139 32125

./mm $1

cd ../../../../GliderWinchCommons/embed/svn_discoveryf4/PC/sensor/CANldr1/trunk
./CANldr $2 $3 $1 ../../../../../../../GliderWinchItems/bmsmot/emcmmc/F446/build/F446.xbin
echo $?
cd -
exit

cd ~/GliderWinchCommons/embed/svn_discoveryf4/PC/sensor/CANldr1/trunk
./CANldr $2 $3 $1 ~/GliderWinchItems/bmsmot/emcmmc/F446/build/F446.xbin
echo $?

cd -

